require("utils")
require("config.settings")
require("config.keymaps")
require("config.theme")
require("plugins.plugins")
require("plugins.nvim_tree")
require("plugins.which_key")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.lualine")
require("plugins.bufferline")
require("lsp")
require("plugins.trouble")
require("config.autocommands")
require("lsp_lines").setup()
require("plugins.autopairs")
require("plugins.telescope")
require("plugins.alpha")
require("plugins.colorizer")
require("plugins.toggleterm")
require("plugins.gitsigns")
-- require("plugins.noice")
require("color-picker").setup()
-- require("plugins.chatgpt")
require("plugins.session_manager")
